[package]
name = "glust"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
refinery = { version = "0.9.0", features = ["postgres"] }
sqlx = { version = "0.8.6", features = ["postgres", "runtime-tokio-rustls"] }
tokio = { version = "1.49.0", features = ["full"] }
